version: 2.1

defaults: &jobsdefault
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *jobsdefault
    steps:
      - checkout
      - run:
          name: Build
          command: |
            npm i
      - save_cache:
          paths:
            - "node_modules"
          key: "npm-packages"
      - run:
          command: |
            npm run lint

  test:
    <<: *jobsdefault
    steps:
      - checkout
      - restore_cache:
          keys: ["npm-packages"]
      - run:
          name: Test
          command: |
            npm run test

  analyze:
    <<: *jobsdefault
    steps:
      - checkout
      - restore_cache:
          keys: ["npm-packages"]
      - run:
          name: Audit
          command: |
            npm audit

workflows:
  my_first_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test